### ISSUE TITLE
pockyt fails to install with Python 2.7

### ISSUE THREAD

**Issue by asergi** [arvindch/pockyt#9]
Attempting to pip install `pockyt` currently fails with:
```
running build
running build_py
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    'pockyt=pockyt.pockyt:main',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_py.py", line 51, in run
    self.build_packages()
  File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
    self.build_module(module, module_file, package)
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_py.py", line 71, in build_module
    package)
  File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
    "'package' must be a string (dot-separated), list, or tuple")
TypeError: 'package' must be a string (dot-separated), list, or tuple
```
In Python 2, unicode is not allowed for metadata fields as stated in the [distutils](https://docs.python.org/2/distutils/setupscript.html#additional-meta-data) documentation: `None of the string values may be Unicode.`

A possible solution would be to just remove `unicode_literals` from `setup.py`.
I'd rather suggest you to use `setuptools.find_packages()` to collect packages inside of your project directory:
```diff
diff --git a/setup.py b/setup.py
index 20ed8a8..d6702d5 100644
--- a/setup.py
+++ b/setup.py
@@ -1,7 +1,7 @@
 from __future__ import absolute_import, print_function, unicode_literals, with_statement
 
 import sys
-from setuptools import setup
+from setuptools import setup, find_packages
 
 
 if sys.version_info[0:2] not in ((2, 7), (3, 4), (3, 5)):
@@ -21,7 +21,7 @@ except:
 
 setup(
     name=name,
-    packages=[name],
+    packages=find_packages(),
     version=version,
     description='automate and manage your pocket collection',
     long_description=desc,
```
If you agree, I'd like to open a PR.

**Comment by arvindch** [comment]
Yep, I think this is a good approach. :+1: 
Open a PR, I'll merge.
Thanks! :smile:
